project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Alcance del documento"
        href: index.qmd
  title: "Guía de cálculo de indicadores y categoría de estado y tendencias poblacionales."
  author: "Lucía V. - MigraMar"
  date: "6/24/2026"
  chapters:
    - intro.qmd
    - part: "Formato archivos"
      chapters:
        - formato_datos_crudos.qmd      
        - formato_datos_calculados.qmd
    - calculo_indicadores.qmd
    - linea_base.qmd
    - clasificar_indicadores.qmd
    - tendencia_poblacional.qmd
    - sistema_envio.qmd
    - anexos.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand

editor: visual

