# Alcance del documento

## **¿Qué está dentro y fuera del alcance de este manual?**

El presente documento es un anexo del documento principal del Plan de Monitoreo. El Plan contiene contexto y detalles por especie, indicador, la metodología para calcular cada uno y la metodología para determinar tendencias respecto a una línea base a partir de dos medidas principales: (1) AVP (determinado por valores de percentiles de la línea base) que genera un “semáforo” del estado del indicador y (2) modelos de tendencia estadística para aquellos sets de datos de monitoreo con más de 10 años. Para detalles de justificación de esta metodología, referirse al documento principal del Plan (citar secciones específicas).

Como recordatorio general, este es el proceso:

Datos crudos → Línea base → Umbrales de “semáforo” a partir de percentiles

↓

Valor anual del indicador

 ↓

Ubicación del valor anual respecto a los percentiles y su clasificación

↓

Análisis de tendencia del indicador (GAMM) – solo si aplica

 ↓

Interpretación final

El presente documento se limita a guiar a los generadores de datos paso a paso para:

**(1)** Preparar los datos en el formato inicial necesario **(2)** Calcular los indicadores según la metodología del Plan **(3)** Preparar los datos asociados a la forma requerida para la plataforma de visualización Marine Manager **(4)** Pasos para entregar los datos.

**Nota importante:** Se encuentra fuera del alance de este documento, revisar la calidad y validez de sus datos y este documento asume que los colectores de datos y responsables de los indicadores deben velar por el cumplimiento estandarizado y riguroso de las metodologías de monitoreo establecidas en el Plan.

## **¿Cómo se ve una implementación exitosa de este manual? (outputs)**

·       Archivo de datos calculados (línea base, percentiles, valores anuales del indicador y valores del GAMM) en formato para alimentar la plataforma Marine Manager

Screenshot- Y explicación columnas (codesheet) anexa. Señalar que es una línea para AVP y otra para GAMM. Que las columnas son por año. Y destacar que se mantiene el “source”/créditos de los datos.

·       Gráficos de ejemplo que irá en la plataforma.

## **¿Cómo usar esta guía?**

Al lado izquiero verá el menú dinámico, que presenta diferentes secciones. Al hacer clic en cada una tendrá acceso específico a la misma.

El manual es un instructivo paso a paso con texto y con secciones de código como ejemplos.

Los pasos por seguir dependerán de su decisión de si comparte datos crudos (y depurados) o si va a brindar los datos de los indicadores ya calculados.

En cualquier cosa, debe revisar las guías de formato de los archivos de datos. Una vez cumplidos los formatos, debería poder usar la guía de cálculos de indicadores sin problemas.

En las secciones que guían cálculos, se presentan secciones (chunks) de código de R para mostrar el procedimiento de forma preliminar. Sin embargo, adicionalmente, en Anexos encontrará el código completo como un archivo independiente para todo el proceso de cálculos.

Además, en los Anexos encontrará como archivos descargables las plantillas de archivo de datos crudos o calculados, y el código de análisis s para que pueda utilizarlos con sus propios datos.

**Este documento se estructura en siete secciones de la siguiente forma:**

1.    Instrucciones de formato inicial mínimo requerido de los datos.

a.    Formato de datos crudos depurados.

b.    Formato de datos de indicadores ya calculados.

2.    Guía de cálculo de indicadores

3.    Guía de cálculo de valores de línea base

4.    Guía de clasificación del indicador con base en AVP

5.    Guía de cálculo tendencias poblacionales mediante GAMMs

6.    Sistema de envío de datos e incorporación a la plataforma virtual

7.    Anexos
