---
title: "Sistema de envío de datos"
---

Una vez firmado el acuerdo de datos, estos son los pasos a seguir:

**1.      Inscripción al proceso mediante Form que le solicitará:**


    a.  Rellenar hoja de metadatos del proveedor de datos (autoría, créditos, etc)

    b.  Confirmar lectura del manual de preparación de indicadores

    c.  Confirmar vía de provisión de datos:

           i.      Indicador calculado

           ii.      Datos crudos y que MigraMar calcula

**2.  Carga de datos:** MigraMar crea un vínculo para subir los datos crudos, o calculados

       
    a.   Proveedor de datos sube:


           i.      Los datos cumpliendo los requerimientos del Manual.

           ii.      Shp files de sitio / área de monitoreo

           iii.      Logos de su afiliación


**3. Revisión calidad de los datos:**  MigraMar revisa cumplimiento de requerimientos y se entra en un ciclo de revision con el proveedor hasta que se cumplan

**4. Subir datos a Marine Manager:**  MigraMar sube los datos calculados al archivo de datos de Global Fishing Watch.
